<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sys01root
 * Date: Tue, 31 Oct 2023 22:14:02 +0100
 */

$conf['title'] = 'Wiki';
$conf['lang'] = 'de';
$conf['template'] = '20cones';
$conf['license'] = 'gnufdl';
$conf['youarehere'] = 1;
$conf['useheading'] = 'navigation';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = '@admin_lokal';
$conf['disableactions'] = 'register';
$conf['defer_js'] = 0;
$conf['dnslookups'] = 0;
$conf['plugin']['simplenavi']['sort'] = 'ascii';
$conf['tpl']['sprintdoc']['header_layout'] = 'header-compact';
