# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 20 Oct 2020 18:45:26 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

unknownuser:$2y$10$BdfDelQy93gZ2rnCZxxpxOtLyfXADCiMvd/jdtenshaoen/JcSyo/q:unbekannt:nothing@example.de:admin,user

