---
# Module für Webserver, Postgres und AppMS 
- name: Abhängigkeiten installieren (Apache und Postgres)
  ansible.builtin.apt:
    name:
      - "{{ apache_version }}"
      - "{{ postgres_version }}"


# notwendige Module für Postgres-Ferninstallation installieren
- name: Abhängigkeiten für python-Schnittstelle zu postgres, sowie unzip installieren
  ansible.builtin.apt:
    name:
      - python-pip
      - libpq-dev
      - python3-dev
      - python3-psycopg2
      - unzip
      - zstd

